### ISSUE TITLE
FB_XP_Track.Configuring : ipTracksEndAtThis not fill

### ISSUE THREAD

**Issue by happymaker25** [Beckhoff-Switzerland/CHALET_XPlanar#2]
Hi,
I'm currently trying to use the Chalet XPlanar library, and it seems than the ipTracksEndAtThis array is not fill correctly by the configuring method.
Steps 300 and 301 are both filling the ipTracksStartFromThis array. 
The step 301 should fill the ipTracksEndAtThis array, am I correct ?

Thanks for your help.

`
	300: // Convert SubsequentTrackOTCIDs to I_XP_Track and add to fbTracksAhead
		fbTracksAhead.Clear();
		FOR nIdx := 0 TO (XPlanarParameterlist.N_MAX_STATIONS_AHEAD_OR_BEHIND-1) DO
			//Get interface to object
			ipEachTrackObj := THIS^.ipXpSystem.Tracks.FindOID(THIS^.SubsequentTrackOTCIDs[nIdx]);
			//convert object -> I_XP_Track. If found, store in list
			IF ToXpTrack(ipEachTrackObj, ipTracksStartFromThis[nIdx]) THEN
				fbTracksAhead.AddObject(ipEachTrackObj);
				
			ELSIF THIS^.SubsequentTrackOTCIDs[nIdx] = 0 THEN
				;//No OTCID
				
			ELSE
				//Error, no track found with following oid
				nSeqConfiguring := nSeqConfiguring + 1000;	
				RETURN;;				
			END_IF
		END_FOR
		nSeqConfiguring := 301;		
	

	301: // Convert PreviousTrackOTCIDs to I_XP_Track and add to fbTracksBehinde
		fbTracksBehinde.Clear();
		FOR nIdx := 0 TO (XPlanarParameterlist.N_MAX_STATIONS_AHEAD_OR_BEHIND-1) DO
			//Get interface to object
			ipEachTrackObj := THIS^.ipXpSystem.Tracks.FindOID(THIS^.PreviousTrackOTCIDs[nIdx]);
			//convert object -> I_XP_Track. If found, store in list
			IF ToXpTrack(ipEachTrackObj, ipTracksStartFromThis[nIdx]) THEN
				fbTracksBehinde.AddObject(ipEachTrackObj);
				
			ELSIF THIS^.PreviousTrackOTCIDs[nIdx] = 0 THEN
				;//No OTCID
				
			ELSE
				//Error, no track found with following oid
				nSeqConfiguring := nSeqConfiguring + 1000;	
				RETURN;;				
			END_IF
		END_FOR			
		nSeqConfiguring := 999;
`

**Comment by Andreas-BACH** [comment]
Hello @happymaker25 
Yes you are absolutely right, I will correct it in the next version. Thanks for reporting it.
It is quite possible that in the near future the array “TracksEndAtThis” and “TracksStartFromThis” will be removed and only the list object of type I_CH_List “TracksAhead” and “TracksBehinde” will be available.
